<?php

namespace Denis\CvBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvRepository extends EntityRepository
{

	public function getCvsForUser($user)
	{
		return $this->createQueryBuilder('c')
				->andWhere('c.owner = :owner')
				->setParameter('owner', $user)
				->getQuery()
				->getResult();
	}

}
